language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
sudo: false
script: make
notifications:
  email:
    recipients:
      - petr@kutalek.cz
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - /^devel.*$/
    - /^feature.*$/
    - /^hotfix.*$/
